Blatts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='HomeView'),
    
    url(r'^sandwich_builder/',
        include('sandwich_builder.urls', namespace="sandwich_builder")),
    
    url(r'^cart/', include('cart.urls', namespace="cart")),
    
    url(r'^admin/', admin.site.urls),
]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    
    url(r'^remove/(?P<pk>[0-9]+)/$', views.remove_from_cart, name='remove_from_cart'),
    
    url(r'^show/$', views.show_cart, name='show_cart'),
]

sandwich_builder/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.sandwich_index, name='sandwich_index'),
    
    url(r'^(?P<base>\w+)/$', views.burger_constructor, name='burger_constructor'),
    
    url(r'^add_sandwich/(?P<base>\w+)/$', views.add_sandwich, name='add_sandwich'),
]

cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

sandwich_builder/models.py
from __future__ import unicode_literals
from django.db import models

from decimal import Decimal

class PricedItem(models.Model):
    """
    An abstract base class model that provides price fields
    for every item sold.
    """
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    
    class Meta:
        abstract = True

class Condiment(PricedItem):
    """
    Class providing the different types of spreadable sandwich additions.
    """
    condiments = models.CharField(max_length = 30, blank=True)
    def __unicode__(self):
        return self.condiments

class Topping(PricedItem):
    """
    Class providing the different types of non-spreadable sandwich additions.
    """
    toppings = models.CharField(max_length= 30, blank=True)
    def __unicode__(self):
        return self.toppings

class Cheese(PricedItem):
    """
    Class providing the different cheese additions.
    """
    cheeses = models.CharField(max_length= 30, blank=True)
    def __unicode__(self):
        return self.cheeses

class Side(PricedItem):
    """
    Class providing the different available sides on offer.
    """
    sides = models.CharField(max_length= 30)
    def __unicode__(self):
        return self.sides
     
class Base(PricedItem):
    """
    Class that defines the type of 'filling' for a sandwich.
    A main sandwich type identifier, along with Bread.
    """
    bases = models.CharField(max_length = 10, primary_key=True)
    
    def human_readable(self):
        return self.bases.replace('_', ' ')
    
    def __unicode__(self):
        return self.bases

class Bread(PricedItem):
    """
    Class that defines the type of bread for a sandwich.
    A main sandwich type identifier, along with Base.
    """
    breads = models.CharField(max_length = 10)
    toasted = models.NullBooleanField()
    def __unicode__(self):
        return self.breads

class Sandwich(models.Model):
    """
    The raison d'etre of this module. Defines sandwiches in terms
    of constituent classes, which can be mixed and matched in any quantity.
    """
    bread = models.ForeignKey(Bread, on_delete=models.CASCADE)
    base = models.ForeignKey(Base, on_delete=models.CASCADE)
    
    condiments = models.ManyToManyField(Condiment, default='No Condiments', blank=True)
    toppings = models.ManyToManyField(Topping, default='No Toppings', blank=True)
    cheeses = models.ManyToManyField(Cheese, default='No Cheese', blank=True)
    side = models.ForeignKey(Side, default=0, blank=True)
    
    
    
    @property
    def get_extras_price(self):
        add_ons = []
        total = Decimal(0.00)
        
        for item in self.toppings.all():
            add_ons.append(item.price)
            
        for item in self.cheeses.all():
            add_ons.append(item.price)
            
        for price in add_ons:
            total += price
            
        return total
    
    @property
    def price(self):
        return self.base.price + self.bread.price + self.get_extras_price
    
    class Meta:
        verbose_name_plural='sandwiches'
    
    def __unicode__(self):
        return "%s on %s (%s)" % (self.base.human_readable(), self.bread, self.side)

sandwich_builder/forms.py
from django import forms


from sandwich_builder.models import Sandwich, Base

class SandwichForm(forms.ModelForm):
    class Meta:
        model = Sandwich
        fields = ['bread', 'cheeses', 'condiments', 'toppings', 'side']

class QuantityForm(forms.Form):
    quantity = forms.IntegerField(label='Quantity',
                                  initial=1, min_value = 1, max_value = 5)

Blatts/views.py
from django.views.generic import TemplateView



class HomeView(TemplateView):
    template_name = 'landing.html'

cart/views.py
from django.shortcuts import render, get_object_or_404

from django.core.urlresolvers import reverse

from django.http import HttpResponse, HttpResponseRedirect

from sandwich_builder.models import Sandwich

from .cart import Cart


def show_cart(request):
    cart = Cart(request.session).items
    total = Cart(request.session).total
    
    context = {'cart':cart, 'total':total}
    
    return render(request, 'cart/show_cart.html', context)

def remove_from_cart(request, pk):
    cart = Cart(request.session)
    #product = Sandwich.objects.get(id=pk)
    cart.remove(pk)
    return HttpResponseRedirect(reverse('cart:show_cart'))

sandwich_builder/views.py
from django.shortcuts import render, get_object_or_404

from django.db.models import F

from django.core.urlresolvers import reverse

from django.http import HttpResponse, HttpResponseRedirect

from .models import Sandwich, Cheese, Condiment, Side, Topping, Base, Bread

from .forms import SandwichForm, QuantityForm

from cart.cart import Cart


def sandwich_index(request):
    request.session.set_expiry(0)
    
    base_selections = Base.objects.all()
    context = {'base_selections':base_selections}
    return render(request, 'sandwich_builder/sandwich_index.html', context)

def burger_constructor(request, base):
    form = SandwichForm(initial={'base': base})
    form2 = QuantityForm()
    
    sand_base = get_object_or_404(Base, pk=base)
    return render(request, 'sandwich_builder/sandwich_constructor.html',
                  {'form':form, 'form2':form2, 'base':sand_base})

def add_sandwich(request, base):
    cart = Cart(request.session)
    
    sand_base = get_object_or_404(Base, pk=base)
    form = SandwichForm(request.POST, initial={'base': base})
    form2 = QuantityForm(request.POST)
    
    if form.is_valid() and form2.is_valid():
        bread = form.cleaned_data['bread']
        toppings = form.cleaned_data['toppings']
        condiments = form.cleaned_data['condiments']
        cheeses = form.cleaned_data['cheeses']
        side= form.cleaned_data['side']
        
        quantity = form2.cleaned_data['quantity']
        
        sandwich = Sandwich()
        sandwich.base= sand_base
        sandwich.bread= bread
        sandwich.save()
        
        sandwich.side= side
        sandwich.toppings= toppings
        sandwich.condiments= condiments
        sandwich.cheeses= cheeses
        sandwich.save()
        
        product = sandwich 
        cart.add(product, price=sandwich.price, quantity=quantity)
        return HttpResponseRedirect(reverse('cart:show_cart'))
    
    return render(request, 'sandwich_builder/sandwich_constructor.html',
                  {'base': sand_base, 'form':form})

cart/templates/cart/show_cart.html
{% extends 'base.html' %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Cart</title>
    </head>


{% block content %}
    
{% if cart %}
    <h1>Shopping Cart</h1>
        <table class="table table-striped table-sm">
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th>Price</th>
            <th>Edit</th>
            <th>Remove?</th>
        </tr>
        {% for item in cart %}
        <tr>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product }}</td>
            <td>${{ item.price }}</td>
            <td>Edit</td>
            <td><a href="{% url 'cart:remove_from_cart' pk=item.product.pk %}">Remove</td>
        </tr>
    {% endfor %}
        </table>

    Total: ${{ total }}
{% else %}
    <h1 class="text-center"> Cart is Empty
    <small>Go to Sandwich Builder, and create a sandwich!</small></h1>
{% endif %}
{% endblock %}
</html>

sandwich_builder/templates/sandwich_builder/sandwich_constructor.html
{% extends 'base.html' %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Sandwich Constructor</title>
    </head>




{% block title %}
<h1>Build your {{ base.human_readable }} sandwich here.</h1>
{% endblock %}

{% block content %}
{% if error_message %}<p><strong> {{ error_message }}</strong></p>{% endif %}

<form action="{% url 'sandwich_builder:add_sandwich' base=base %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    
    {% bootstrap_form form2 layout='inline' %}
    
    {% buttons %}
    <button type="submit" class="btn btn-danger btn-block">
        {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>

{% endblock %}
</html>

sandwich_builder/templates/sandwich_builder/sandwich_index.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Menu</title>
    </head>


{% block title %}
<h1 class="text-center">SELECT SANDWICH TYPE</h1>
{% endblock %}

{% block content %}
    
{% if base_selections %}
<div>
    {% for base in base_selections %}
</div>
        <img src="/sandwich_builder/static/images/{{ base }}.jpg" class="img-responsive" alt="Responsive image">
        <h4 class="text-center"><a href="{% url 'sandwich_builder:burger_constructor' base.bases %}">
            {{ base.human_readable }} | ${{ base.price }}
        </a></h4>
    {% endfor %}
{% endif %}
{% endblock %}
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery=1 %}
        <link href="{% static 'css/sandwich_builder.css' rel="stylesheet" %}">
    </head>





{% block bootstrap3_content %}

<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Greenblatt's Deli</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'sandwich_builder:sandwich_index' %}">Sandwich Builder</a></li>
                <li><a href="{% url 'cart:show_cart' %}">Cart</a></li>
            </ul>
        </div>
    </div>
</nav>


{% block title %}<h1></h1>{% endblock %}

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}

{% endblock %}
</html>

templates/landing.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery=1 %}
    </head>

<div class="wrapper">
    <img src="/sandwich_builder/static/images/old_hollywood.jpg" class="img-responsive" alt="Responsive image">
</div>

</html>